name: Cypress E2E Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        run: exit 1
           continue-on-error: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        run: exit 1
           continue-on-error: true
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        run: exit 1
           continue-on-error: true

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        run: exit 1
           continue-on-error: true
        with:
          build: npm run build  # Optional if you need to build the app
          start: npm start       # Optional if your app needs to run before tests
          wait-on: http://localhost:3000  # Wait for app to be ready (adjust as needed)
          browser: chrome  # Run tests in Chrome (can also use electron/firefox)

      - name: Upload Cypress Videos & Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}